source 'https://github.com/CocoaPods/Specs'
use_frameworks!

platform :ios, '9.0'

target 'FFScanCodeKit_Example' do
  pod 'FFScanCodeKit', :path => '../'

  target 'FFScanCodeKit_Tests' do
    inherit! :search_paths

    
  end
end
